version: '3.3'
services:
  suricata-siem-custom:
    network_mode: host
    privileged: true
    image: suricata-siem-custom
    build:
      dockerfile: Dockerfile-suricata
      context: .
    logging:
      driver: awslogs
      options:
        awslogs-group: siem1
        awslogs-region: eu-west-1
        awslogs-create-group: "true"
  suricata-siem-elastic:
      network_mode: host
      privileged: true
      image: suricata-siem-elastic
      build:
        dockerfile: Dockerfile-suricata
        context: .
      volumes:
        - logs:/var/log/suricata
  filebeat-siem-elastic:
      image: filebeat
      build:
        dockerfile: Dockerfile-filebeat
        context: .
      user: root
      cap_add:
      - NET_RAW
      - NET_ADMIN
      environment:
        - CLOUD_ID=${CLOUD_ID}
        - CLOUD_AUTH=${CLOUD_AUTH}
      volumes:
        - logs:/var/log/suricata
      command: ["--strict.perms=false","-e"]
  packetbeat-siem-elastic:
      image: packetbeat
      build:
        dockerfile: Dockerfile-packetbeat
        context: .
      user: root
      network_mode: host
      cap_add:
      - NET_RAW
      - NET_ADMIN
      environment:
        - CLOUD_ID=${CLOUD_ID}
        - CLOUD_AUTH=${CLOUD_AUTH}
      command: ["--strict.perms=false","-e"]

volumes:
  logs:
