from ubuntu:20.04

# Install system tools

RUN apt-get update -y && \
    apt-get install net-tools iputils-ping tcpdump vim -y

# Install suricata

RUN apt-get install software-properties-common -y && \
    add-apt-repository ppa:oisf/suricata-stable && \
    apt-get update -y && \ 
    apt-get install suricata suricata-dbg -y && \
    suricata-update

COPY suricata.yaml /etc/suricata/suricata.yaml
COPY local.rules /var/lib/suricata/rules/local.rules
COPY threshold.config /etc/suricata/threshold.config

ENTRYPOINT ["suricata","-c","/etc/suricata/suricata.yaml"]